# -*- coding: utf-8 -*-
"""01_non_personalized (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfAzwGfbR2tFsKHRQ5kTVDPzaVtO8sk-
"""

# -*- coding: utf-8 -*-

"""01_non_personalized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRKq9HwfiT91QH1EgNq9My6Th4CV54Qv

# Non-Personalized Recommender Systems

In this notebook, we build and evaluate three non-personalized recommendation approaches using the MovieLens dataset:

1. Average Rating Recommender
2. Popularity-Based Recommender
3. Weighted Rating Recommender

These methods recommend the same items to every user and provide strong baseline models for comparison with more advanced recommenders.

Contributors: Juan Múñoz, Santiago Llorca

# IMPORT LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""# LOAD THE DATA"""

try:
    ratings = pd.read_csv("ml-latest-small/ratings.csv")
    movies = pd.read_csv("ml-latest-small/movies.csv")
except FileNotFoundError:
    ratings = pd.read_csv("ratings.csv")
    movies = pd.read_csv("movies.csv")

ratings.head()

movies.head()

"""# DATASET OVERVIEW"""

n_users = ratings["userId"].nunique()
n_items = ratings["movieId"].nunique()
n_ratings = len(ratings)
sparsity = 1 - n_ratings / (n_users * n_items)

print(f"Number of users: {n_users}")
print(f"Number of movies: {n_items}")
print(f"Number of ratings: {n_ratings}")
print(f"Sparsity: {sparsity:.2%}")

"""# BASIC EDA"""

plt.figure(figsize=(8, 5))
ratings["rating"].hist(bins=10)
plt.xlabel("Rating")
plt.ylabel("Frequency")
plt.title("DISTRIBUTION OF RATINGS")
plt.show()

ratings_per_movie = ratings.groupby("movieId")["rating"].count()

plt.figure(figsize=(8, 5))
ratings_per_movie.hist(bins=30)
plt.title("Number of Ratings per Movie")
plt.xlabel("Ratings Count")
plt.ylabel("Frequency")
plt.show()

ratings_per_user = ratings.groupby("userId")["rating"].count()

plt.figure(figsize=(8, 5))
ratings_per_user.hist(bins=30)
plt.title("Number of Ratings per User")
plt.xlabel("Ratings Count")
plt.ylabel("Frequency")
plt.show()

"""The dataset shows a long-tail pattern: a small number of movies receive many ratings, while most movies receive only a few. The same happens with users, since some users are much more active than others.

# MOVIE STATISTICS TABLE

## TRAIN / TEST SPLIT

We split ratings by time (80/20) to simulate a realistic evaluation scenario. The movie statistics table is computed on training data only to avoid data leakage.
"""

# Temporal train/test split (80/20)
ratings_sorted = ratings.sort_values("timestamp")
cutoff = int(len(ratings_sorted) * 0.8)
train = ratings_sorted.iloc[:cutoff].copy()
test = ratings_sorted.iloc[cutoff:].copy()

print(f"Train size: {len(train)}")
print(f"Test size:  {len(test)}")

movie_stats = train.groupby("movieId").agg(
    avg_rating=("rating", "mean"),
    num_ratings=("rating", "count")
).reset_index()

movie_stats = movie_stats.merge(movies[["movieId", "title"]], on="movieId")
movie_stats.head()

"""# RECOMMENDER 1: AVERAGE RATING"""

top10_avg = movie_stats.sort_values("avg_rating", ascending=False).head(10)
top10_avg[["title", "avg_rating", "num_ratings"]]

"""This recommender ranks movies by their average rating only.

Its main limitation is that movies with very few ratings can appear at the top, even if the score is not reliable.

# RECOMMENDER 2: POPULARITY
"""

top10_pop = movie_stats.sort_values("num_ratings", ascending=False).head(10)
top10_pop[["title", "avg_rating", "num_ratings"]]

"""This recommender ranks movies by the number of ratings they received.

It captures engagement and popularity, but it does not consider whether users actually liked the movie.

# RECOMMENDER 3: WEIGHTED RATING
"""

C = train["rating"].mean()   # FIX: use train only to avoid data leakage
m = movie_stats["num_ratings"].quantile(0.75)

def imdb_weighted_rating(row, m, C):
    v = row["num_ratings"]
    R = row["avg_rating"]
    W = (v / (v + m)) * R + (m / (v + m)) * C
    return W

movie_stats["weighted_rating"] = movie_stats.apply(
    imdb_weighted_rating, axis=1, args=(m, C)
)

top10_weighted = movie_stats.sort_values("weighted_rating", ascending=False).head(10)
top10_weighted[["title", "avg_rating", "num_ratings", "weighted_rating"]]

"""The weighted rating recommender balances quality and popularity.

It reduces the effect of movies with very few ratings by shrinking their score toward the global average. This produces more reliable rankings than simple average rating.

# COMPARE THE THREE TOP-10
"""

print("Top 10 by Average Rating")
display(top10_avg[["title", "avg_rating", "num_ratings"]])

print("Top 10 by Popularity")
display(top10_pop[["title", "avg_rating", "num_ratings"]])

print("Top 10 by Weighted Rating")
display(top10_weighted[["title", "avg_rating", "num_ratings", "weighted_rating"]])

"""The three recommenders produce different ranking logics:

- Average rating favors movies with the highest mean score, even if they have very few ratings.
- Popularity favors movies with the largest number of ratings, regardless of quality.
- Weighted rating provides a compromise between both signals.

Among the three, weighted rating is usually the strongest non-personalized baseline because it balances reliability and popularity.

# Conclusion

In this notebook, we implemented three non-personalized recommenders.

The average rating one is simple but unreliable for movies with few ratings. The popularity one captures engagement but ignores quality. The weighted rating combines both, making it the most balanced of the three.

These approaches are useful because they are simple and work well when there is no user data. The downside is that they recommend the same thing to everyone, so more advanced methods like collaborative filtering are needed for personalized suggestions.

## WEIGHTED RATING PREDICTIONS ON TEST SET

We generate predictions for the test set using the weighted rating. Since this is a non-personalized model, every user receives the same predicted rating for a given movie (its weighted rating). We export the results so the evaluation notebook can compute metrics alongside the other recommenders.
"""

# Map weighted rating back to test rows
weighted_map = movie_stats.set_index("movieId")["weighted_rating"]
global_mean_np = train["rating"].mean()

test["pred_weighted"] = test["movieId"].map(weighted_map).fillna(global_mean_np)

# Clip to valid rating range
test["pred_weighted"] = test["pred_weighted"].clip(0.5, 5.0)

# Export predictions for Notebook 5

# 1. Rebuild the same temporal split
ratings_eval = ratings.sort_values("timestamp").copy()
cutoff = int(len(ratings_eval) * 0.8)

train_eval = ratings_eval.iloc[:cutoff].copy()
test_eval = ratings_eval.iloc[cutoff:].copy()

# 2. Compute weighted non-personalized score using train only
movie_stats_eval = train_eval.groupby("movieId").agg(
    avg_rating=("rating", "mean"),
    num_ratings=("rating", "count")
).reset_index()

C_eval = train_eval["rating"].mean()
m_eval = movie_stats_eval["num_ratings"].quantile(0.75)

movie_stats_eval["score_non_personalized"] = (
    (movie_stats_eval["num_ratings"] / (movie_stats_eval["num_ratings"] + m_eval)) * movie_stats_eval["avg_rating"]
    + (m_eval / (movie_stats_eval["num_ratings"] + m_eval)) * C_eval
)

weighted_scores_eval = movie_stats_eval.set_index("movieId")["score_non_personalized"]

# 3. Create prediction dataframe on the test set
pred_np = test_eval[["userId", "movieId", "rating"]].copy()
pred_np["score_non_personalized"] = pred_np["movieId"].map(weighted_scores_eval).fillna(C_eval)

# 4. Export CSV
# Rename score column to predicted_rating for consistency with other notebooks
# The weighted rating IS our best rating prediction for non-personalized
pred_np = pred_np.rename(columns={"score_non_personalized": "predicted_rating_non_personalized"})

# Keep score_non_personalized as an alias so notebook 05 ranking metrics still work
pred_np["score_non_personalized"] = pred_np["predicted_rating_non_personalized"]

pred_np.to_csv("predictions_non_personalized.csv", index=False)

print(pred_np.shape)
pred_np.head()