# -*- coding: utf-8 -*-
"""02_collaborative_filtering (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtouQa8sCFDKi_S-lZz00Zy2E0hKBa8-
"""

# -*- coding: utf-8 -*-

"""02_collaborative_filtering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFJVZ7CDHUTxtbEhhdmCQKCrd8rWzX6H

# Collaborative Filtering Recommender

In this notebook, we build a collaborative filtering recommender using the MovieLens dataset.

Unlike non-personalized approaches, collaborative filtering generates user-specific recommendations by identifying similar users and using their rating patterns to predict missing ratings.

We start with a user-based collaborative filtering model using cosine similarity, and then compare it with Pearson correlation.

Contributors: Juan Múñoz, Santiago Llorca
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import mean_absolute_error, mean_squared_error

"""# 1. Load data"""

try:
    ratings = pd.read_csv("ml-latest-small/ratings.csv")
    movies = pd.read_csv("ml-latest-small/movies.csv")
except FileNotFoundError:
    ratings = pd.read_csv("ratings.csv")
    movies = pd.read_csv("movies.csv")

"""## 2. Temporal Train-Test Split

We use a temporal split instead of a random split. This is more realistic for recommender systems because predictions should always be made using past interactions only.
"""

ratings = ratings.sort_values("timestamp")

cutoff = int(len(ratings) * 0.8)
train = ratings.iloc[:cutoff].copy()
test = ratings.iloc[cutoff:].copy()

print("Train size:", len(train))
print("Test size:", len(test))

"""## 3. Build the User-Item Matrix

The user-item matrix is the foundation of collaborative filtering. Rows represent users, columns represent movies, and values are ratings.
"""

user_item_matrix = train.pivot_table(
    index="userId",
    columns="movieId",
    values="rating"
)

print("User-item matrix shape:", user_item_matrix.shape)
user_item_matrix.head()

"""## 4. Baseline Model

We first compute the global mean rating. This is the simplest possible predictor and serves as a baseline to beat.
"""

global_mean = train["rating"].mean()
print("Global mean rating:", round(global_mean, 4))

"""## 5. User-Based Collaborative Filtering with Cosine Similarity

Cosine similarity compares users based on the angle between their rating vectors. It uses raw ratings and does not correct for user-specific rating scale bias.
"""

user_item_filled = user_item_matrix.fillna(0)

user_similarity_cosine = cosine_similarity(user_item_filled)
user_similarity_cosine = pd.DataFrame(
    user_similarity_cosine,
    index=user_item_matrix.index,
    columns=user_item_matrix.index
)

np.fill_diagonal(user_similarity_cosine.values, 0)

user_similarity_cosine.head()

"""## 6. Cosine Prediction Function

For each user-item pair, the model finds similar users who rated the target movie and computes a weighted average of their ratings.
"""

def predict_rating_cosine(user_id, movie_id, user_item_matrix, similarity_matrix, k=20):
    # If movie not in training columns or user not in matrix, fallback to global mean
    if user_id not in user_item_matrix.index or movie_id not in user_item_matrix.columns:
        return np.nan

    # Users who rated the target movie
    movie_ratings = user_item_matrix[movie_id].dropna()

    if movie_ratings.empty:
        return np.nan

    # Similarities between target user and users who rated the movie
    sim_scores = similarity_matrix.loc[user_id, movie_ratings.index]

    # Keep top-k similar users
    top_k_users = sim_scores.sort_values(ascending=False).head(k)

    # Keep only positive similarities
    top_k_users = top_k_users[top_k_users > 0]

    if top_k_users.empty:
        return np.nan

    # Ratings of neighbors
    neighbor_ratings = movie_ratings.loc[top_k_users.index]

    # Weighted prediction
    pred = np.dot(top_k_users, neighbor_ratings) / top_k_users.sum()
    return pred

"""## 7. Generate Predictions with Cosine Similarity"""

test["pred_cosine"] = test.apply(
    lambda row: predict_rating_cosine(
        row["userId"],
        row["movieId"],
        user_item_matrix,
        user_similarity_cosine,
        k=20
    ),
    axis=1
)

test["pred_cosine"] = test["pred_cosine"].fillna(global_mean)
# Clip to valid rating range [0.5, 5.0]
test["pred_cosine"] = test["pred_cosine"].clip(0.5, 5.0)

test[["userId", "movieId", "rating", "pred_cosine"]].head()

"""## 8. Evaluate Cosine Collaborative Filtering"""

mae_baseline = mean_absolute_error(test["rating"], [global_mean] * len(test))
rmse_baseline = np.sqrt(mean_squared_error(test["rating"], [global_mean] * len(test)))

mae_cosine = mean_absolute_error(test["rating"], test["pred_cosine"])
rmse_cosine = np.sqrt(mean_squared_error(test["rating"], test["pred_cosine"]))

print(f"Baseline MAE: {mae_baseline:.4f}")
print(f"Baseline RMSE: {rmse_baseline:.4f}")
print(f"Cosine CF MAE: {mae_cosine:.4f}")
print(f"Cosine CF RMSE: {rmse_cosine:.4f}")

"""Cosine collaborative filtering produces personalized predictions based on user-user similarity.

Its main limitation is sparsity. If similar users have not rated the target item, the model cannot generate a reliable prediction and must fall back to the global mean.

## 9. User-Based Collaborative Filtering with Pearson Correlation

Pearson correlation corrects for user rating bias by mean-centering each user's ratings before computing similarity.

This is useful because some users systematically rate higher or lower than others.
"""

user_means = user_item_matrix.mean(axis=1)
user_item_centered = user_item_matrix.sub(user_means, axis=0)
user_item_centered_filled = user_item_centered.fillna(0)

user_similarity_pearson = cosine_similarity(user_item_centered_filled)
user_similarity_pearson = pd.DataFrame(
    user_similarity_pearson,
    index=user_item_matrix.index,
    columns=user_item_matrix.index
)

np.fill_diagonal(user_similarity_pearson.values, 0)

user_similarity_pearson.head()

"""## 10. Pearson Prediction Function"""

def predict_rating_pearson(user_id, movie_id, user_item_matrix, centered_matrix, similarity_matrix, user_means, k=20):
    if user_id not in user_item_matrix.index or movie_id not in user_item_matrix.columns:
        return np.nan

    movie_ratings = user_item_matrix[movie_id].dropna()
    if movie_ratings.empty:
        return np.nan

    sim_scores = similarity_matrix.loc[user_id, movie_ratings.index]
    top_k_users = sim_scores.sort_values(ascending=False).head(k)
    top_k_users = top_k_users[top_k_users > 0]

    if top_k_users.empty:
        return np.nan

    centered_ratings = centered_matrix.loc[top_k_users.index, movie_id].dropna()

    aligned_users = top_k_users.index.intersection(centered_ratings.index)
    top_k_users = top_k_users.loc[aligned_users]
    centered_ratings = centered_ratings.loc[aligned_users]

    if top_k_users.empty:
        return np.nan

    pred = user_means.loc[user_id] + np.dot(top_k_users, centered_ratings) / top_k_users.sum()
    return pred

"""## 11. Generate Predictions with Pearson Correlation"""

test["pred_pearson"] = test.apply(
    lambda row: predict_rating_pearson(
        row["userId"],
        row["movieId"],
        user_item_matrix,
        user_item_centered,
        user_similarity_pearson,
        user_means,
        k=20
    ),
    axis=1
)

test["pred_pearson"] = test["pred_pearson"].fillna(global_mean)
# Clip to valid rating range [0.5, 5.0]
test["pred_pearson"] = test["pred_pearson"].clip(0.5, 5.0)

test[["userId", "movieId", "rating", "pred_pearson"]].head()

"""## 12. Evaluate Pearson Collaborative Filtering"""

mae_pearson = mean_absolute_error(test["rating"], test["pred_pearson"])
rmse_pearson = np.sqrt(mean_squared_error(test["rating"], test["pred_pearson"]))

print(f"Pearson CF MAE: {mae_pearson:.4f}")
print(f"Pearson CF RMSE: {rmse_pearson:.4f}")

"""## 13. Compare All Models"""

results_cf = pd.DataFrame({
    "Model": ["Global Mean", "Cosine CF", "Pearson CF"],
    "MAE": [mae_baseline, mae_cosine, mae_pearson],
    "RMSE": [rmse_baseline, rmse_cosine, rmse_pearson]
})

results_cf

"""## 14. Interpretation of Results

The baseline predicts the same value for all user-item pairs, so it ignores any personalization.

Cosine collaborative filtering improves on this by leveraging similarity between users. Pearson collaborative filtering goes one step further by correcting for rating-scale differences across users.

In practice, Pearson is often more robust when users have different rating habits, while cosine is simpler and easier to compute.

## 15. Conclusion

In this notebook, we implemented user-based collaborative filtering using cosine similarity and Pearson correlation.

Both models provide personalized predictions and improve over a simple global mean baseline. However, collaborative filtering remains sensitive to sparsity, since predictions depend on overlap between users and items.

Overall, Pearson correlation is theoretically stronger because it adjusts for rating bias, while cosine similarity provides a simpler baseline for user-based collaborative filtering.

## 16. Export Predictions

We export the test set with all predictions so the evaluation notebook (05) can compute ranking metrics alongside the other recommenders.
"""

# Export predictions for Notebook 5

pred_cf = test[["userId", "movieId", "rating"]].copy()

# Select the final collaborative filtering model
if "pred_pearson" in test.columns and "pred_cosine" in test.columns:
    if "rmse_pearson" in globals() and "rmse_cosine" in globals():
        best_cf_col = "pred_pearson" if rmse_pearson <= rmse_cosine else "pred_cosine"
    else:
        best_cf_col = "pred_pearson"
elif "pred_pearson" in test.columns:
    best_cf_col = "pred_pearson"
else:
    best_cf_col = "pred_cosine"

# Export a single score column for the final CF approach
pred_cf["score_cf"] = test[best_cf_col]

# Optional: keep the exact predicted rating column too
pred_cf["predicted_rating_cf"] = test[best_cf_col]

pred_cf.to_csv("predictions_cf.csv", index=False)

print("Exported collaborative filtering model:", best_cf_col)
print(pred_cf.shape)
pred_cf.head()