# -*- coding: utf-8 -*-
"""03_content_based_recommender_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NabC6jctGySlSrFHLdPVERlFNmuMlGOE
"""

# -*- coding: utf-8 -*-

"""03_content-based_recommender_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ohs6XMDOZhSxYEk1ibf92PpIJ3gcziF

# Content-Based Recommender System

In this notebook, we build a content-based recommender using the MovieLens dataset.

Unlike collaborative filtering, content-based recommendation suggests items based on their own characteristics. In this case, we use movie genres as item features.

The main idea is:
- represent each movie using its genres
- build a user profile from the movies the user liked
- recommend unseen movies that are most similar to that user profile

Contributors: Andrés Ramírez, Yago Moreno

## 0. Import the libraries (Setup)
"""

#Import the necessary libraries

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

"""## 1. Load the Data"""

try:
    ratings = pd.read_csv("ml-latest-small/ratings.csv")
    movies = pd.read_csv("ml-latest-small/movies.csv")
except FileNotFoundError:
    ratings = pd.read_csv("ratings.csv")
    movies = pd.read_csv("movies.csv")

"""## 2. Temporal Train-Test Split

We use a temporal split so that recommendations are generated only from past interactions.
"""

ratings = ratings.sort_values("timestamp").copy()

cutoff = int(len(ratings) * 0.8)
train = ratings.iloc[:cutoff].copy()
test = ratings.iloc[cutoff:].copy()

print("Train size:", len(train))
print("Test size:", len(test))

"""## 3. Feature Engineering

We represent each movie using its genres. The genre column is transformed into a binary feature matrix.
"""

movies_features = movies.copy()
movies_features["genres"] = movies_features["genres"].str.replace("|", " ", regex=False)

genre_matrix = movies_features["genres"].str.get_dummies(sep=" ")
genre_matrix.index = movies_features["movieId"]

genre_matrix.head()

"""## 4. Item-Item Similarity

We compute cosine similarity between movies based on their genre vectors.
"""

item_similarity = cosine_similarity(genre_matrix)

item_similarity = pd.DataFrame(
    item_similarity,
    index=genre_matrix.index,
    columns=genre_matrix.index
)

item_similarity.head()

"""## 5. Similar Movies Function

For a given movie, we retrieve the most similar movies according to the genre-based similarity matrix.
"""

def get_similar_movies(movie_id, item_similarity, movies, top_n=10):
    if movie_id not in item_similarity.index:
        return pd.DataFrame(columns=["movieId", "title", "similarity"])

    sim_scores = item_similarity.loc[movie_id].sort_values(ascending=False)

    # Remove the movie itself
    sim_scores = sim_scores.iloc[1:top_n+1]

    similar_movies = pd.DataFrame({
        "movieId": sim_scores.index,
        "similarity": sim_scores.values
    })

    similar_movies = similar_movies.merge(movies[["movieId", "title"]], on="movieId")

    return similar_movies[["movieId", "title", "similarity"]]

"""## 6. Example: Similar Movies"""

example_movie = movies["movieId"].iloc[0]

print("Selected movie:", movies[movies["movieId"] == example_movie]["title"].values[0])
get_similar_movies(example_movie, item_similarity, movies, top_n=10)

"""## 7. Recommend Movies for a User

We recommend movies that are similar to the ones the user previously liked.
"""

def recommend_for_user(user_id, train_ratings, item_similarity, movies, top_n=10, min_rating=4.0):
    user_ratings = train_ratings[train_ratings["userId"] == user_id].copy()
    liked_movies = user_ratings[user_ratings["rating"] >= min_rating]["movieId"]

    if liked_movies.empty:
        return pd.DataFrame(columns=["movieId", "title", "score"])

    scores = pd.Series(dtype=float)

    for movie_id in liked_movies:
        if movie_id in item_similarity.index:
            similar_scores = item_similarity.loc[movie_id]
            scores = scores.add(similar_scores, fill_value=0)

    scores = scores.sort_values(ascending=False)

    seen_movies = user_ratings["movieId"].unique()
    scores = scores[~scores.index.isin(seen_movies)]

    recommendations = pd.DataFrame({
        "movieId": scores.index,
        "score": scores.values
    })

    recommendations = recommendations.merge(movies[["movieId", "title"]], on="movieId")

    return recommendations.head(top_n)[["movieId", "title", "score"]]

"""## 8. Example: User Recommendations"""

example_user = train["userId"].iloc[0]

print(f"Recommendations for user {example_user}")
recommend_for_user(example_user, train, item_similarity, movies, top_n=10, min_rating=4.0)

"""## 9. Prediction Function for Notebook 5

To compare this recommender with the others in Notebook 5, we generate two outputs for each user-item pair in the test set:

- `score_content`: a ranking score
- `predicted_rating_content`: a predicted rating for RMSE and MAE
"""

def predict_content_metrics(user_id, movie_id, train_data, item_similarity, min_rating=4.0):
    user_ratings = train_data[train_data["userId"] == user_id].copy()
    liked_movies = user_ratings[user_ratings["rating"] >= min_rating][["movieId", "rating"]]

    if liked_movies.empty:
        return np.nan, np.nan

    if movie_id not in item_similarity.index:
        return np.nan, np.nan

    similarities = []
    ratings_list = []

    for _, row in liked_movies.iterrows():
        liked_movie = row["movieId"]
        liked_rating = row["rating"]

        if liked_movie in item_similarity.columns:
            sim = item_similarity.loc[movie_id, liked_movie]
            similarities.append(sim)
            ratings_list.append(liked_rating)

    if len(similarities) == 0:
        return np.nan, np.nan

    similarities = np.array(similarities)
    ratings_list = np.array(ratings_list)

    # Ranking score
    score_content = similarities.mean()

    # Predicted rating
    if similarities.sum() > 0:
        predicted_rating_content = np.dot(similarities, ratings_list) / similarities.sum()
    else:
        predicted_rating_content = ratings_list.mean()

    return score_content, predicted_rating_content

"""## 10. Compute Predictions on the Full Test Set"""

pred_content = test[["userId", "movieId", "rating"]].copy()

pred_content[["score_content", "predicted_rating_content"]] = pred_content.apply(
    lambda row: pd.Series(
        predict_content_metrics(
            row["userId"],
            row["movieId"],
            train,
            item_similarity,
            min_rating=4.0
        )
    ),
    axis=1
)

global_mean = train["rating"].mean()

pred_content["score_content"] = pred_content["score_content"].fillna(0)
pred_content["predicted_rating_content"] = pred_content["predicted_rating_content"].fillna(global_mean)

pred_content.head()

"""## 12. Interpretation

This recommender suggests movies that are similar in genre to the movies the user already liked.

Its main advantage is interpretability and independence from other users.

Its main limitation is overspecialization, since it tends to recommend items very similar to past preferences.

## 13. Conclusion

In this notebook, we implemented a content-based recommender using movie genres as item features.

First, movies were represented through a binary genre matrix. Then, cosine similarity was used to measure similarity between items. Based on this similarity structure, the model was able to recommend movies similar to those previously liked by each user.

To make the model suitable for the final project evaluation, we also generated two outputs for each user-item pair in the test set:
- a ranking score (`score_content`)
- a predicted rating (`predicted_rating_content`)

This allows the model to be compared with the other recommenders in Notebook 5 using both error-based metrics and ranking metrics.

Overall, the content-based approach is simple, interpretable, and useful when item features are available. However, it may suffer from overspecialization and depends strongly on the quality of the item representation.

## 14. Export Predictions for Notebook 5
"""

pred_content.to_csv("predictions_content.csv", index=False)

print("File exported: predictions_content.csv")
pred_content.head()